#!/usr/bin/env sh

set -ex

main() {
  case "$1" in
  install)
    installBins
    ;;
  list)
    ls -1 /opt/cni/bin
    ;;
  *)
    usage
    ;;
  esac
}

usage() {
  set +x
  echo "/bin/cni-node <action>"
  echo "Actions:"
  echo "  install - install cni bin plugins"
  echo "  list - lists current cni bin plugins"
}

# installs ALL baked-in cni bins into /host/opt/cni/bin directory
installBins() {
  echo "Installing CNI plugins..."
  mkdir -p "/host/opt/cni/bin"
  install /opt/cni/bin/* /host/opt/cni/bin/
  echo "...done"
}

main "$@"
